#container 内でbun動かす用
version: "3.9"
services:
  app:
    build: 
      context: .
    tty: true
    volumes:
      - ./:/home/bun/app
      # 以下で多分vscodeの「インターフェイス 'JSX.IntrinsicElements' が存在しないため、暗黙的に JSX 要素の型は 'any' になります。」が消えるか。
      - ./node_modules:/home/bun/app/node_modules
    ports:
      - "3000:3000"
    working_dir: /home/bun/app
    command: bash -c "bun i && bun run dev"
volumes:
  node_modules: