services:
  next:
    container_name: next
    build: .
    image: next
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
    restart: always
    command: bun --bun run dev
    develop:
      watch:
        - action: sync
          path: ./next
          target: /home/bun/app/next
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - 80:3000

networks:
  default:
    name: TNA
    driver: bridge
    external: true